apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app-${{ values.app_name }}
  annotations:
    "backstage.io/fastapi": ${{ values.app_name | dump }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: infrastructure
  lifecycle: experimental
  providesApis:
    - ${{ values.app_name }}

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.app_name }}
  description: The App APIs Specification. ${{ values.description }}
  tags:
    - fastapi
spec:
  type: openapi
  lifecycle: experimental
  owner: infrastructure
  definition:
    $text: ./fastapi.yaml