name: Build python app

on:
  push:
    branches: main
{% raw %}
env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  build-fastapi-app:
    name: Build FastAPI App
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      actions: read
      checks: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into ${{ env.REGISTRY }}
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag
        run: echo "VERSION_TAG=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT
        id: tag
      
      - name: Build Application
        run: |
          docker build --tag "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.VERSION_TAG }}" --tag "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" .
      
      # Use docker push command directly to work with docker login action.
      - name: Push to ${{ env.REGISTRY }} registry
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.VERSION_TAG }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
{% endraw %}  
